# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='driver.proto',
  package='driver',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64river.proto\x12\x06\x64river\"\x16\n\x14\x43reateSessionRequest\"\"\n\x12\x43reateSessionReply\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"-\n\x0e\x45xecuteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"{\n\x0c\x45xecuteReply\x12\r\n\x05\x63lose\x18\x01 \x01(\x08\x12\x12\n\x05\x64\x65\x62ug\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06stderr\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06stdout\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_debugB\t\n\x07_stderrB\t\n\x07_stdout2\x95\x01\n\rDriverService\x12I\n\rCreateSession\x12\x1c.driver.CreateSessionRequest\x1a\x1a.driver.CreateSessionReply\x12\x39\n\x07\x45xecute\x12\x16.driver.ExecuteRequest\x1a\x14.driver.ExecuteReply0\x01\x62\x06proto3'
)




_CREATESESSIONREQUEST = _descriptor.Descriptor(
  name='CreateSessionRequest',
  full_name='driver.CreateSessionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=46,
)


_CREATESESSIONREPLY = _descriptor.Descriptor(
  name='CreateSessionReply',
  full_name='driver.CreateSessionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='driver.CreateSessionReply.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=82,
)


_EXECUTEREQUEST = _descriptor.Descriptor(
  name='ExecuteRequest',
  full_name='driver.ExecuteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='driver.ExecuteRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input', full_name='driver.ExecuteRequest.input', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=129,
)


_EXECUTEREPLY = _descriptor.Descriptor(
  name='ExecuteReply',
  full_name='driver.ExecuteReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='close', full_name='driver.ExecuteReply.close', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug', full_name='driver.ExecuteReply.debug', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='driver.ExecuteReply.stderr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='driver.ExecuteReply.stdout', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_debug', full_name='driver.ExecuteReply._debug',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_stderr', full_name='driver.ExecuteReply._stderr',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_stdout', full_name='driver.ExecuteReply._stdout',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=131,
  serialized_end=254,
)

_EXECUTEREPLY.oneofs_by_name['_debug'].fields.append(
  _EXECUTEREPLY.fields_by_name['debug'])
_EXECUTEREPLY.fields_by_name['debug'].containing_oneof = _EXECUTEREPLY.oneofs_by_name['_debug']
_EXECUTEREPLY.oneofs_by_name['_stderr'].fields.append(
  _EXECUTEREPLY.fields_by_name['stderr'])
_EXECUTEREPLY.fields_by_name['stderr'].containing_oneof = _EXECUTEREPLY.oneofs_by_name['_stderr']
_EXECUTEREPLY.oneofs_by_name['_stdout'].fields.append(
  _EXECUTEREPLY.fields_by_name['stdout'])
_EXECUTEREPLY.fields_by_name['stdout'].containing_oneof = _EXECUTEREPLY.oneofs_by_name['_stdout']
DESCRIPTOR.message_types_by_name['CreateSessionRequest'] = _CREATESESSIONREQUEST
DESCRIPTOR.message_types_by_name['CreateSessionReply'] = _CREATESESSIONREPLY
DESCRIPTOR.message_types_by_name['ExecuteRequest'] = _EXECUTEREQUEST
DESCRIPTOR.message_types_by_name['ExecuteReply'] = _EXECUTEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateSessionRequest = _reflection.GeneratedProtocolMessageType('CreateSessionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESESSIONREQUEST,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driver.CreateSessionRequest)
  })
_sym_db.RegisterMessage(CreateSessionRequest)

CreateSessionReply = _reflection.GeneratedProtocolMessageType('CreateSessionReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATESESSIONREPLY,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driver.CreateSessionReply)
  })
_sym_db.RegisterMessage(CreateSessionReply)

ExecuteRequest = _reflection.GeneratedProtocolMessageType('ExecuteRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEREQUEST,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driver.ExecuteRequest)
  })
_sym_db.RegisterMessage(ExecuteRequest)

ExecuteReply = _reflection.GeneratedProtocolMessageType('ExecuteReply', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEREPLY,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driver.ExecuteReply)
  })
_sym_db.RegisterMessage(ExecuteReply)



_DRIVERSERVICE = _descriptor.ServiceDescriptor(
  name='DriverService',
  full_name='driver.DriverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=257,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateSession',
    full_name='driver.DriverService.CreateSession',
    index=0,
    containing_service=None,
    input_type=_CREATESESSIONREQUEST,
    output_type=_CREATESESSIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='driver.DriverService.Execute',
    index=1,
    containing_service=None,
    input_type=_EXECUTEREQUEST,
    output_type=_EXECUTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRIVERSERVICE)

DESCRIPTOR.services_by_name['DriverService'] = _DRIVERSERVICE

# @@protoc_insertion_point(module_scope)
