# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x06\x64river\"\x16\n\x14\x43reateSessionRequest\"\"\n\x12\x43reateSessionReply\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"-\n\x0e\x45xecuteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"\x99\x01\n\x0c\x45xecuteReply\x12\r\n\x05\x63lose\x18\x01 \x01(\x08\x12\x12\n\x05\x64\x65\x62ug\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06stderr\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06stdout\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05value\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x08\n\x06_debugB\t\n\x07_stderrB\t\n\x07_stdoutB\x08\n\x06_value2\x95\x01\n\rDriverService\x12I\n\rCreateSession\x12\x1c.driver.CreateSessionRequest\x1a\x1a.driver.CreateSessionReply\x12\x39\n\x07\x45xecute\x12\x16.driver.ExecuteRequest\x1a\x14.driver.ExecuteReply0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATESESSIONREQUEST._serialized_start=24
  _CREATESESSIONREQUEST._serialized_end=46
  _CREATESESSIONREPLY._serialized_start=48
  _CREATESESSIONREPLY._serialized_end=82
  _EXECUTEREQUEST._serialized_start=84
  _EXECUTEREQUEST._serialized_end=129
  _EXECUTEREPLY._serialized_start=132
  _EXECUTEREPLY._serialized_end=285
  _DRIVERSERVICE._serialized_start=288
  _DRIVERSERVICE._serialized_end=437
# @@protoc_insertion_point(module_scope)
